name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Dynamic369
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg
          outputs: |
            ./assets/github-contribution-grid-snake.svg
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake-dark.svg
        
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
